; ZX Next Sample Table
; Generated by NextBuild Sample Packer
; Format: dw bank+loop, start_offset, length
; 15656Hz 8-bit unsigned PCM

ctc_sample_table:
    dw $1F00,0,3238 ; 0 4dead.pcm
    dw $1F00,3238,4417 ; 1 0jump.pcm
    dw $1F00,7655,7086 ; 2 3punch.pcm
    dw $2000,6549,7516 ; 3 1pickup.pcm
    dw $2100,5873,11502 ; 4 complete.pcm
    ds 16,0 ; padding
