' Project: HelloWorld
' Generated by NextBuild Project Creator

'!org=$8000
'!heap=4096

#include "nextlib.bas"

' Hover over any key word to see explanations, or press F1 for help
' f5 to compile and run 

main()              ' call the main() subroutine 

sub main()
    
    border 0 : cls

    print at 0,0; "Hello from Boriel ZX Basic!"
    print at 2,0; "Hello from nextbuildstudio!"

    ' main loop or program logic here

    do
        ' example: check for key press to exit
        if inkey$ <> "" then exit do
    loop

    border 2 

end sub

print "End of Demo!"

do : loop           ' we loop forever, as we loaded with a nex which 
                    ' wont exit to basic cleanly!...
