' Project: GamePad
' Generated by NextBuild Project Creator
'
' A live gamepad tester on a 320x256 Layer 2 screen. Four arrows sit around
' the edge of a box with a fire button in the middle; each one lights up
' while its input is held and fades back down when you let go, so you can
' see contact bounce and stuck directions rather than just a word on screen.
'
' Kempston 1 on port 31, or Q/A/O/P and SPACE on the keyboard. The raw port
' byte is printed at the bottom in binary, which covers the buttons that
' have no pad on screen (fire 2 and fire 3 on a MegaDrive pad).

'!org=24576
' NextBuild Layer2 Template

#define NEX
#define IM2

#include <nextlib.bas>
#include <nextlib_primitives.bas>      ' L2Box / L2FillTriangle / L2FillCircle
#include <keys.bas>                    ' required for MultiKeys

' Kempston port 31 bit masks. Note these are NOT the BIT_UP/BIT_DOWN
' constants in nb_constants.bas - those are bit numbers for a direction
' byte, not masks for this port.
#define JOY_RIGHT   1
#define JOY_LEFT    2
#define JOY_DOWN    4
#define JOY_UP      8
#define JOY_FIRE    16

' Pad ids, used to index heat() and to pick a shape in DrawPad().
#define PAD_UP      0
#define PAD_DOWN    1
#define PAD_LEFT    2
#define PAD_RIGHT   3
#define PAD_FIRE    4

#define HEAT_MAX    6                  ' how bright a held pad gets

' Box the pads are arranged around, and its centre.
#define BOXX1       80
#define BOXY1       60
#define BOXX2       240
#define BOXY2       200
#define BOXCX       160
#define BOXCY       130

dim j as ubyte                          ' raw Kempston byte this frame
dim i as ubyte
dim heat(4) as ubyte                    ' 0..HEAT_MAX per pad, decays
dim shown(4) as ubyte                   ' last level drawn, so we only redraw
dim dirramp(6) as ubyte                 ' dim grey -> bright green
dim fireramp(6) as ubyte                ' dim grey -> bright red


' 1 if either the pad direction or the key is down. Both are checked every
' frame so the keyboard and the pad can be used interchangeably.
function Held(byval mask as ubyte, byval key as uinteger) as ubyte
    dim r as ubyte = 0
    if (j band mask) <> 0
        r = 1
    elseif MultiKeys(key) <> 0
        r = 1
    end if
    return r
end function


' Repaint one pad at brightness level 0..HEAT_MAX. Boriel has no SELECT CASE,
' hence the IF chain.
sub DrawPad(byval pad as ubyte, byval level as ubyte)
    dim c as ubyte

    if pad = PAD_FIRE
        c = fireramp(level)
    else
        c = dirramp(level)
    end if

    if pad = PAD_UP
        L2FillTriangle(BOXCX, BOXY1 + 8, BOXCX - 16, BOXY1 + 36, _
                       BOXCX + 16, BOXY1 + 36, c)
    elseif pad = PAD_DOWN
        L2FillTriangle(BOXCX, BOXY2 - 8, BOXCX - 16, BOXY2 - 36, _
                       BOXCX + 16, BOXY2 - 36, c)
    elseif pad = PAD_LEFT
        L2FillTriangle(BOXX1 + 8, BOXCY, BOXX1 + 36, BOXCY - 16, _
                       BOXX1 + 36, BOXCY + 16, c)
    elseif pad = PAD_RIGHT
        L2FillTriangle(BOXX2 - 8, BOXCY, BOXX2 - 36, BOXCY - 16, _
                       BOXX2 - 36, BOXCY + 16, c)
    else
        L2FillCircle(BOXCX, BOXCY, 26, c)
        ' the fill wipes the label, so put it back on top every time
        FL2Text(18, 16, "FIRE", 32)
    end if
end sub


' Bump a pad towards full brightness while held, decay it one step a frame
' once released. The decay is what makes a dropped connection visible.
sub UpdatePad(byval pad as ubyte, byval down as ubyte)
    if down <> 0
        heat(pad) = HEAT_MAX
    elseif heat(pad) > 0
        heat(pad) = heat(pad) - 1
    end if

    if heat(pad) <> shown(pad)
        DrawPad(pad, heat(pad))
        shown(pad) = heat(pad)
    end if
end sub


' --- setup ---------------------------------------------------------------

' Load font5 from system into bank 32
LoadSDBank("[]font5.fnt",0,0,0,32)
' set up Layer2 320x256
InitLayer2(MODE320X256)
' show the layer2
ShowLayer2(1)

' 8bpp Layer 2 colour is RRRGGGBB, so these are R*32 + G*4 + B.
dirramp(0) = 37  : dirramp(1) = 41  : dirramp(2) = 49
dirramp(3) = 85  : dirramp(4) = 122 : dirramp(5) = 190
dirramp(6) = 255

fireramp(0) = 37  : fireramp(1) = 69  : fireramp(2) = 133
fireramp(3) = 169 : fireramp(4) = 205 : fireramp(5) = 246
fireramp(6) = 255

ClearLayer2(0)
FL2Text(9, 2, "NEXTBUILD GAMEPAD TEST", 32)
FL2Text(10, 30, "PAD OR Q A O P SPACE", 32)

' the box the pads live around
L2Box(BOXX1, BOXY1, BOXX2, BOXY2, 73)

' labels outside the box, drawn once - the pads never overdraw them
FL2Text(19, 5,  "UP", 32)
FL2Text(18, 26, "DOWN", 32)
FL2Text(5, 15,  "LEFT", 32)
FL2Text(31, 15, "RIGHT", 32)

' every pad starts dark, and shown() starts one off so the first frame draws
for i = 0 to 4
    heat(i) = 0
    shown(i) = 255
next i


' --- main loop -----------------------------------------------------------

do
    ' port 31 if kempston 1, 51 kempston 2
    j = in 31                       ' Kempston 1

    UpdatePad(PAD_UP,    Held(JOY_UP,    KEYQ))
    UpdatePad(PAD_DOWN,  Held(JOY_DOWN,  KEYA))
    UpdatePad(PAD_LEFT,  Held(JOY_LEFT,  KEYO))
    UpdatePad(PAD_RIGHT, Held(JOY_RIGHT, KEYP))
    UpdatePad(PAD_FIRE,  Held(JOY_FIRE,  KEYSPACE))

    ' raw port byte, so buttons with no pad on screen still show up
    FL2Text(12, 28, "PORT 31 " + BinToString(j), 32)

    WaitRaster(192)

loop
