; ZX Next Sample Table
; Generated by NextBuild Sample Packer
; Format: dw bank+loop, start_offset, length
; 15656Hz 8-bit unsigned PCM

ctc_sample_table:
    dw $1F00,0,4417 ; 0 0jump.pcm
    dw $1F00,4417,7516 ; 1 1pickup.pcm
    dw $2000,3741,7086 ; 2 3punch.pcm
    dw $2100,2635,3238 ; 3 4dead.pcm
    dw $2100,5873,11502 ; 4 complete.pcm
    dw $2300,991,12432 ; 5 boom.wav
    ds 16,0 ; padding
